// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package main

import (
	"cyshu_admin/app/cyshu/internal/biz"
	"cyshu_admin/app/cyshu/internal/conf"
	"cyshu_admin/app/cyshu/internal/data"
	"cyshu_admin/app/cyshu/internal/server"
	"cyshu_admin/app/cyshu/internal/service"
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
)

// Injectors from wire.go:

// initApp init kratos application.
func initApp(confServer *conf.Server, confData *conf.Data, logger log.Logger) (*kratos.App, func(), error) {
	dataData, cleanup, err := data.NewData(confData, logger)
	if err != nil {
		return nil, nil, err
	}
	userRepo := data.NewUserRepo(dataData, logger)
	userUsecase := biz.NewUserUsecase(userRepo, logger)
	adminRepo := data.NewAdminRepo(dataData, logger)
	adminUsecase := biz.NewAdminUsecase(adminRepo, logger)
	cyshuAdmin := service.NewCyshuAdminService(userUsecase, adminUsecase, logger)
	httpServer := server.NewHTTPServer(confServer, cyshuAdmin, logger)
	grpcServer := server.NewGRPCServer(confServer, cyshuAdmin, logger)
	app := newApp(logger, httpServer, grpcServer)
	return app, func() {
		cleanup()
	}, nil
}
